node_type 6 {
    name = "S-MATCH"
    description = "S-MATCH ATU by SQ8ERS & SQ8KFH"

    register 10 {
        name = "STATUS"
        type = bool
        size = 10
        readable = true
        writable = false
        bits-names = { "TUNE_PHASE2", "TUNE_PHASE1", "TUNE_PHASE0", "FAILURE", "TUNED", "UNDERPOWER ERROR", "MEMORY SHORTCUT", "SWR SHORTCUT",  "ATTENUATOR", "TUNING"}
    }

    register 11 {
        name = "CTRL"
        type = bool
        size = 6
        readable = true
        writable = true
        bits-names = { "MEMORY SHORTCUT", "SWR SHORTCUT", "DEBUG", "FULL TUNE", "TUNE", "ATTENUATOR"}

    }

    register 12 {
        name = "L"
        type = uint
        size = 8
        readable = true
        writable = true
    }

    register 13 {
        name = "C"
        type = uint
        size = 8
        readable = true
        writable = true
    }

    register 14 {
        name = "P"
        type = uint
        size = 8
        readable = true
        writable = true
    }

    register 15 {
        name = "Memory"
        type = blob
        size = 8192
        readable = true
        writable = false
    }

}
