dev antenna_switch {
    type = AntennaSwitch
    node_ids = {32, 2}
}

#dev thunder_switch {
#    type = ThunderSwitch
#    node_ids = 0
#}

dev shack_switch {
    type = PowerSwitch
    node_ids = 100
}

dev doublet_atu {
    type = ATU
    node_ids = 505
}
