nodes_description = /etc/h9/nodes.conf
default_source_id = 222
default = def

connection def {
    uri = "h9d://127.0.0.1"
    #source_id = 150
}

connection vpn {
    uri = "h9d://192.168.3.200:7979"
}

connection slcan {
    uri = "slcan:///dev/tty.usbmodemAAA6207738541"
}
