DefaultSourceID = 222
default = def

connection def {
    uri = "h9d://127.0.0.1"
    #SourceID = 150
}

connection vpn {
    uri = "h9d://192.168.3.200:7979"
}

connection slcan {
    uri = "slcan:///dev/tty.usbmodemAAA6207738541"
}
