process {
    daemonize = false
    #pidfile = /var/run/h9d.pid
    #setuid = 1000
    #setgid = 20
}

server {
    port = 7979
}

h9d {
    response_timeout = 3
    nodes_description = /etc/h9/nodes.conf
    devs_configuration = /etc/h9/dev.conf

    devs_workers = 5
}

bus {
    source_id = 509
    forwarding = true

    endpoint can0 {
        driver = SocketCAN
        #
        # ip link set can0 type can bitrate 125000
        # ip link set can0 txqueuelen 1000
        # ip link set up can0
        #
        interface = can0
    }

    endpoint udp0 {
        driver = udp
        #
        # Should be compatible with can2udp
        #
        local_port = 15730
        remote_addr = 192.168.3.198
        remote_port = 15730
    }

    /*endpoint loop0 {
        driver = loop
    }*/

    endpoint vcan {
        #used by virtual_node
        driver = virtual
    }

    /*endpoint can1 {
        driver = SLCAN
        tty = "/dev/tty.usbserial-DA14T39W"
        init_command = "O\r"
    }*/
}

virtual_endpoint {
    python_path = /usr/local/lib/h9/virtual_node
    python_node_module = rpi_gpio_node
    node_id = 100
    node_type = 12
}

log {
    frames_logfile = /var/log/h9/frame.log
    #disable_sent_frames = true
    #disable_recv_frames = true
}
