process {
    daemonize = false
    #pidfile = /var/run/h9d.pid
    #setuid = 1000
    #setgid = 20
}

server {
    port = 7979
}

h9d {
    response_timeout = 3
    nodes_description = /Users/crowx/projekty/h9/h9d/conf/nodes.conf
    devs_configuration = /Users/crowx/projekty/h9/h9d/conf/dev.conf

    devs_workers = 5
}

bus {
    source_id = 222
    forwarding = true

    endpoint slcan0 {
        driver = SLCAN
        tty = "/dev/tty.usbmodemAAA6207738541"
        init_command = "O\r"
    }
}

virtual_endpoint {
    python_path = /usr/local/lib/h9/virtual_node
    python_node_module = rpi_gpio_node
    node_id = 100
    node_type = 12
}

log {
    frames_logfile = /var/log/h9/frame.log
    #disable_sent_frames = true
    #disable_recv_frames = true
}
