#[[outputs.influxdb_v2]]
#  urls = ["..."]
#  token = "..."
#  organization = "..."
#  bucket = "..."


[[inputs.exec]]
    commands = ["h9stats -s"]
    data_format = "json_v2"

    [inputs.exec.tags]
        name = "*"

    [[inputs.exec.json_v2]]
        [[inputs.exec.json_v2.object]]
            path = "bus.endpoints"
            tags = ["name"]

        [[inputs.exec.json_v2.object]]
            path = "bus.frames"
            tags = ["type"]

  [[inputs.exec.json_v2.object]]
            path = "bus"
            included_keys = ["received_frames", "send_frames"]


[[processors.split]]
    drop_original = true

    [[processors.split.template]]
      name = "endpoints"
      tags = [ "name" ]
      fields = [ "received_frames", "send_frames"]

    [[processors.split.template]]
      name = "frames"
      tags = [ "type" ]
      fields = [ "received", "send" ]
