/*
 * Created by crowx on 23/11/2024.
 *
 */

#ifndef H9_H9ERRNO_H
#define H9_H9ERRNO_H

#include <utility>
#include <h9def.h>

//std::to_underlying(b::B2);

enum struct h9errno : std::uint16_t {
    NO_ERROR = 0,
    //from h9can - frame error
    INVALID_MSG = H9FRAME_ERROR_INVALID_MSG,
    BOOTLOADER_UNSUPPORTED = H9FRAME_ERROR_BOOTLOADER_UNSUPPORTED,
    INVALID_REGISTER = H9FRAME_ERROR_INVALID_REGISTER,
    READ_ONLY_REGISTER = H9FRAME_ERROR_READ_ONLY_REGISTER,
    WRITE_ONLY_REGISTER = H9FRAME_ERROR_WRITE_ONLY_REGISTER,
    REGISTER_SIZE_MISMATCH = H9FRAME_ERROR_REGISTER_SIZE_MISMATCH,
    NODE_SPECIFIC_ERROR = H9FRAME_ERROR_NODE_SPECIFIC_ERROR,

    //raw_frame
    TIMEOUT_ERROR = 1000,
    MALFORMED_FRAME_ERROR,
};

#endif // H9_H9ERRNO_H
