name: Build & Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: lxc-h9-develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build -j

      - name: Install
        run: |
          sudo cmake --install build
